### ISSUE TITLE
Reason: edit Reason title

### ISSUE THREAD

**Issue by bertocq** [PopulateTools/reasons.club#12]
- [ ] Let the reason's author edit the title in the modal window with ajax (easy with the best_in_place we are using; its already being used for the reason's description: https://github.com/PopulateTools/reasons.club/blob/master/app/views/reasons/_reason_extended.html.erb#L30)
- [x] Add the reason title to the paper trail versioning (idem: https://github.com/PopulateTools/reasons.club/blob/master/app/models/reason.rb#L9)

**Comment by furilo** [comment]
Duplicated? #11

**Comment by ferblape** [comment]
If we click in the reason title, it follows the link. Maybe we should add an "Edit" link?
