### ISSUE TITLE
 Give different weights for each reason

### ISSUE THREAD

**Issue by bertocq** [PopulateTools/reasons.club#30]
Give different weights for each reason, because at least when making a personal pro-con list, not every reason has the same value. 

We have many options to discuss:
- Rating with stars [0-5](With too many reasons it wouldn't be enough)
- Ordering in both sides from most to least important. (Lack of comparation)
- Using tags (+/-) so the real weight comes from the importance that each user gives to each tag. Example: 

¿Should I use disc brakes in road bikes?
PROS: Enhance security (#security +)
CONS: Increase bike price (#money +)
            The rotor is a hazard in a crash (#security -)

**Comment by furilo** [comment]
Some notes about this: https://gitter.im/PopulateTools/reasons.club?at=5589d4113e3f225219fd4812
