### ISSUE TITLE
Subscription & Notifications

### ISSUE THREAD

**Issue by bertocq** [PopulateTools/reasons.club#4]
This englobes a big set of features:

- [ ] Subscriptions
  - [ ] Follow/Unfollow a Issue (works as a subscription but since there can be no notification, to use "follow" works better in my mind :sweat_smile:)

- [ ] Notifications
  - [ ] General notifications settings (live / hour / day / none)
  - [ ] Notification settings for an specific Issue (live / hour / day / none)
  - [ ] Reduce notifications (link in the mail to reduce the frequency of the emails)
  - [ ] Notification types:
      - [ ] Any activity in something you created (reason / issue)
      - [ ] New reason in issue
      - [ ] New vote in reason
      - [ ] New wiki edit in reason
      - [ ] New flagged reason (own / issue)
      - [ ] etc...
  - [ ] Create notifications
  - [ ] Send notifications #5

**Comment by ferblape** [comment]
Implemented in #34
