### ISSUE TITLE
Send notifications (live / hour / daily)

### ISSUE THREAD

**Issue by bertocq** [PopulateTools/reasons.club#5]
We should already have: notifications_queued - user | notification | period [hour,day] | status [pending,sent] | created_at

So for users with "live" notifications, it should send them right away, and we need a process for each notification frequency:
- _Hour_: Every minute we search for users with pending notifications created 1h ago or more and compile & send them. Then change all the statuses to "sent"
- _Day_: At a fixed time everyday we search for all pending notifications for every user, compile & send them, then change the status to "sent".

**Comment by ferblape** [comment]
Done in #34
