### ISSUE TITLE
Explore Clubs: tag them, list tags

### ISSUE THREAD

**Issue by bertocq** [PopulateTools/reasons.club#7]
Be able to add tags to an issue (Club) to offer a way to discover related/interesting issues.

List tags, maybe in the home? tagcloud?

**Comment by furilo** [comment]
Some quick sketches: 

**Tags in Club page:**

![desktop landscape](https://cloud.githubusercontent.com/assets/24740/8313457/12df9440-19e3-11e5-80da-f8522abd0800.png)

**Tag page:**

![desktop landscape copy 5](https://cloud.githubusercontent.com/assets/24740/8313468/343e6120-19e3-11e5-91d8-fc9f3a16a69a.png)

**Global tag list** (this page will have to be improved in the future when we have lots of tags, by clustering etc):

![desktop landscape copy 2](https://cloud.githubusercontent.com/assets/24740/8313471/3b57490e-19e3-11e5-92d4-9e10cd2b3d8e.png)

**Nice to have**: When in global tag list, we can show some clubs inline

![desktop landscape copy 3](https://cloud.githubusercontent.com/assets/24740/8313477/48ad8046-19e3-11e5-91c1-1efd52cb82c5.png)

Pending: block to show tags in home. 

Comments welcome @bertocq @ferblape

**Comment by bertocq** [comment]
Awesome work!! I really like the design.

I think the create/edit page will be easy to imagine, but if you have something in mind for it would be nice to have that page design too (/issues/new)

I think I got how "Show some clubs inline" would work but what if there are too much to show? What would be the actions to "just show some" and "show me all"

Also, as a feature request... it would be cool to mark tags as "favourite" or "interesting", to make some intelligent suggestions in the "Keep reasoning" blocks
